NilFoundation/nil.foundation

- _config.yml
- _includes/footer.html
Updated site footer to display location info
> Location info added

- _config.yml
- _includes/css/freshteam_widget.css
- _includes/js.html
- _includes/navbar.html
- _layouts/default.html
- _layouts/style.css
- careers.html
- index.html
> Add careers page

- _config.yml
- _includes/analytics.htm
- _includes/head.html
GA will help to track site users interactions
> Google analytics added

- site/.prettierignore
- site/.prettierrc
- site/src/components/common/AnimatedDottedContainer/AnimatedDottedContainer.module.scss
- site/src/components/common/ArrowButton/ArrowButton.module.scss
- site/src/components/common/SideNavigation/SideNavigation.jsx
- site/src/components/common/SideNavigation/SideNavigation.module.scss
- site/src/components/common/SideNavigation/useSideNavigationTimeline.js
- site/src/components/pages/About/Partners/Partners.jsx
- site/src/components/pages/Home/Home.module.scss
- site/src/components/pages/PostPage/PostPage.jsx
- site/src/components/pages/ZkLlvm/Intro/Intro.module.scss
- site/src/components/pages/ZkLlvm/ZkLlvm.module.scss
> 21 pin animation modifications

- site/src/components/pages/PostPage/PostPage.jsx
- site/src/pages/blog/post/[slug].js
> fix: recommended articles section

- site/src/components/common/AnimatedDottedContainer/AnimatedCard.jsx
- site/src/components/common/IntroAnimation/IntroAnimation.jsx
- site/src/components/common/IntroAnimation/IntroDescription.jsx
- site/src/components/pages/Research/Research.module.scss
- site/src/components/pages/ZkLlvm/Intro/Intro.jsx
- site/src/components/pages/ZkLlvm/Intro/data.js
- site/src/pages/index.js
> 26 zkllvm intro animation fixes

- site/public/icons/doted-line.svg
- site/src/components/common/Header/stub.js
- site/src/components/pages/Glossary/Glossary.jsx
- site/src/components/pages/Glossary/Glossary.module.scss
- site/src/components/pages/Glossary/index.js
- site/src/components/pages/WordPage/WordPage.jsx
- site/src/components/pages/WordPage/WordPage.module.scss
- site/src/components/pages/WordPage/index.js
- site/src/pages/glossary/[slug].js
- site/src/pages/glossary/index.js
- site/src/strapi/rebuildCollection.js
- site/src/strapi/serializers.js
- site/src/stubs/glossaryPageData.js
- site/src/utils/groupArrayByField.js
> add glossary page

- site/src/components/common/Header/Header.module.scss
> Fix header navigation menu margins

- site/src/components/common/ArrowButton/ArrowButton.module.scss
- site/src/components/common/Footer/Footer.jsx
- site/src/components/common/Footer/Footer.module.scss
- site/src/components/common/Header/Header.jsx
- site/src/components/common/Header/Header.module.scss
- site/src/components/common/SideNavigation/SideNavigation.module.scss
- site/src/components/pages/About/OurTeam/OurTeam.module.scss
- site/src/components/pages/About/Partners/Partners.module.scss
- site/src/components/pages/BlogsPage/ArticlesNotFound/ArticlesNotFound.module.scss
- site/src/components/pages/BlogsPage/BlogsPage.module.scss
- site/src/components/pages/Careers/Jobs/Jobs.module.scss
- site/src/components/pages/OpenPositions/DottedSection/DottedSection.module.scss
- site/src/components/pages/OpenPositions/OpenPositions.module.scss
- site/src/components/pages/PostPage/PostPage.jsx
- site/src/components/pages/PostPage/PostPage.module.scss
- site/src/styles/freshteamWidget.scss
> 25 style fixes

- site/src/components/common/ArrowButton/ArrowButton.module.scss
- site/src/components/pages/ZkLlvm/ZkLlvm.module.scss
> 29 black line

- site/src/components/pages/NotFound/NotFound.module.scss
> 39 fix not found page desktop scroll

- dev.sh
- site/src/components/pages/BlogsPage/BlogsPage.module.scss
- site/src/components/pages/PostPage/PostPage.module.scss
- site/src/pages/blog/index.js
Add some distance between post list and white line
Also fix sorting isFeature should be first
> Fix distance with post list

- site/src/constants/common.js
- site/src/pages/api/blogs.js
- site/src/pages/blog/index.js
- site/src/pages/blog/tag/[slug].js
> increase pagesize

- admin/config/ckeditor.txt
I removed some element with custom definition that we need to make an article in easy way. Return it in this PR.
> Add quote to toolbar + code

- admin/src/api/blog/content-types/blog/schema.json
Blog post now sorted in this thing by isFeature: true, false, null. I set it by default to false to not be interpreted by 3 tiers and only will be 2 tiers.
> Set default feature false

- rome.json
- site/src/components/common/AnimatedDottedContainer/AnimatedCard.tsx
- site/src/components/common/AnimatedDottedContainer/AnimatedDottedContainer.tsx
- site/src/components/common/FooterAnimationSection/FooterAnimationSection.tsx
- site/src/components/common/FooterAnimationSection/data.tsx
- site/src/components/common/IntroAnimation/IntroAnimation.tsx
- site/src/components/common/IntroAnimation/IntroDescription.tsx
- site/src/components/common/RevealText/RevealText.tsx
- site/src/components/common/SideNavigation/SideNavigation.tsx
- site/src/components/common/SideNavigation/useSideNavigationTimeline.ts
- site/src/components/pages/BlogsPage/BlogsPage.tsx
- site/src/components/pages/Home/Hero/Hero.tsx
- site/src/components/pages/Home/Intro/Intro.tsx
- site/src/components/pages/Home/Intro/IntroDescriptionWidget.tsx
- site/src/components/pages/Home/Intro/data.tsx
- site/src/components/pages/ZkLlvm/Hero/Hero.tsx
- site/src/components/pages/ZkLlvm/Intro/Intro.tsx
- site/src/components/pages/ZkLlvm/Intro/data.tsx
- site/src/hooks/usePrefersReduceMotion.ts
- site/src/styles/mixins.scss
closes #35 
This diff brings `usePrefersReduceMotion` React hook to dynamically detect if user prefers reduce motion mode.
> Disable animations in prefers reduce motion mode

- site/src/components/pages/PostPage/PostPage.module.scss
Subtitle was way thiner than title so I set it to the same width
> Set subtitle width to title width

- site/src/components/pages/PostPage/PostPage.module.scss
- site/src/components/pages/PostPage/PostPage.tsx
> 75-card-components-usage

- site/src/components/pages/About/JoinNil/JoinNil.module.scss
> 105 fix join nil container wrap about page

- site/src/styles/freshteamWidget.scss
> 103 delete second box shadow in fresh widget

- site/src/components/common/Footer/Footer.module.scss
- site/src/components/common/Footer/stub.ts
> change styles of footer links 

- site/src/components/common/IntroAnimation/IntroAnimation.tsx
- site/src/components/pages/Home/Intro/data.tsx
- site/src/components/pages/ZkLlvm/Intro/data.tsx
- site/src/components/pages/ZkSharding/Intro/data.tsx
- site/src/hooks/useScroll.ts
> 114 animation intro fix

- site/src/components/common/ResearchCard/ResearchCard.module.scss
- site/src/components/common/SideNavigation/SideNavigation.tsx
- site/src/components/pages/BlogsPage/BlogNavigation.tsx
- site/src/components/pages/BlogsPage/BlogsPage.module.scss
- site/src/components/pages/PostPage/PostPage.module.scss
- site/src/components/pages/Research/ResearchLayout/ResearchLayout.module.scss
- site/src/components/pages/Research/ResearchLayout/ResearchLayout.tsx
> 121 fix tags in blogs and researchs

- site/src/pages/_app.tsx
- site/src/styles/freshteamWidget.scss
- site/src/styles/globals.scss
> 85 add dynamic import to open positions freshteam widget

- site/src/components/common/Footer/Footer.module.scss
- site/src/components/common/Footer/Footer.tsx
> 131 footer margins

- site/src/components/common/LinkCard/LinkCard.module.scss
- site/src/components/common/PostCard/PostCard.module.scss
- site/src/components/common/ResearchCard/ResearchCard.module.scss
- site/src/components/pages/Careers/JoinUs/CareerCard/CareerCard.module.scss
> 130 add margins to card top section when use arrow

- site/src/components/common/Header/Header.module.scss
- site/src/components/common/IntroAnimation/IntroAnimation.tsx
- site/src/components/common/LinkCard/LinkCard.module.scss
- site/src/components/pages/Careers/JoinUs/JoinUs.module.scss
- site/src/components/pages/Home/Intro/Intro.module.scss
- site/src/components/pages/Home/Intro/data.tsx
- site/src/components/pages/ZkSharding/Intro/Intro.module.scss
- site/src/components/pages/ZkSharding/Intro/Intro.tsx
- site/src/components/pages/ZkSharding/Secure/Secure.module.scss
> 132 mobile ui fixes

- site/package-lock.json
- site/package.json
- site/src/pages/_app.tsx
- site/src/pages/_document.tsx
- site/src/styletron.ts
This diff adds ui kit to site project in order to start creating new careers page (It consists only of ui kit elements).
> Add ui-kit

- site/src/components/common/SideNavigation/SideNavigation.tsx
- site/src/components/common/SideNavigation/useSideNavigationTimeline.ts
- site/src/utils/loaderImages.ts
> 123 fix blog post side navigation

- site/src/components/pages/OpenJobs/JobPage/FreshteamEmbed.tsx
- site/src/freshteam/api.ts
- site/src/styles/freshteamWidget.scss
This diff add fixed loader container size and add fix to freshteam widget styles.
> Minor site style improvements

- site/src/components/pages/OpenJobs/JobPage/Styles.module.scss
This diff fixes the issue with small fonts in bullet list in mobile version.
> Add font-size 16px to bullet lists in job description #133

- admin/config/ckeditor.txt
Add configuration to use AutoLink plugin 
https://ckeditor.com/docs/ckeditor5/latest/api/module_link_linkconfig-LinkConfig.html#member-addTargetToExternalLinks
also using resizing https://ckeditor.com/docs/ckeditor5/latest/features/images/images-resizing.html#:~:text=Methods%20to%20resize%20images,-The%20editor%20offers&text=The%20ImageResize%20plugin%20enables%20the,(default)%20or%20pixel%20values.
> Resize image handler + enforce target blank

- dev.sh
- site/package-lock.json
This div updates `caniuse-lite` module to detect which features in js bundle can be used and fixe `dev.sh` script. There was an error when setting env variable - content of the file was rewritten and there was no `FRESHTEAM_URL` variable.
> Fix dev.sh script

- site/src/constants/seo.ts
Changed the Invite for TG developers channel to the TG Bot from the typeform.
> Changed Devnet Invite Link to TG Bot

- site/src/components/common/Footer/stub.ts
- site/src/components/common/HeadingSection/data.ts
We actually don't talk with people on discord anymore
> Remove discord

- admin/package.json
- site/src/components/pages/LandingPage/Community/Community.tsx
- site/src/stubs/landingPageData.ts
1. **`package.json`**:
- Fixed `Adin` to `Admin` in the `default_user` script.
2. **`Community.tsx`**:
- Corrected all instances of `anounceLink` to `announceLink` to match the updated data structure.
3. **`landingPageData.ts`**:
- Fixed the key `anounceLink` to `announceLink` for consistency across the application.
> Fix spelling errors in `package.json`, `Community.tsx`, and `landingPageData.ts`

- site/src/components/common/Footer/stub.ts
Because we will use this TOC for newer game too
> Footer name change
